### ISSUE TITLE
Dependencies not installed completely.

### ISSUE THREAD

**Issue by leopku** [ziwenxie/netease-dl#1]
On a clean environment

1. `pip install netease-dl`
2. `netease-dl me` will returns
  ```
  Traceback (most recent call last):
    File "/Users/leo/.pyenv/versions/3.5.2/bin/netease-dl", line 9, in <module>
      load_entry_point('netease-dl==1.0.0', 'console_scripts', 'netease-dl')()
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
      return get_distribution(dist).load_entry_point(group, name)
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
      return ep.load()
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
      return self.resolve()
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/netease/start.py", line 12, in <module>
      import click
  ImportError: No module named 'click'
  ```
3. `pip install click`
4. `netease-dl me` will return
  ```
  Traceback (most recent call last):
    File "/Users/leo/.pyenv/versions/3.5.2/bin/netease-dl", line 9, in <module>
      load_entry_point('netease-dl==1.0.0', 'console_scripts', 'netease-dl')()
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
      return get_distribution(dist).load_entry_point(group, name)
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
      return ep.load()
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
      return self.resolve()
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/netease/start.py", line 14, in <module>
      from .download import NetEase
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/netease/download.py", line 17, in <module>
      from .weapi import Crawler
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/netease/weapi.py", line 21, in <module>
      from .utils import Display
    File "/Users/leo/.pyenv/versions/3.5.2/lib/python3.5/site-packages/netease/utils.py", line 10, in <module>
      from prettytable import PrettyTable
ImportError: No module named 'prettytable'
  ```
5. `pip install prettytable`

It can run now.

**Comment by ziwenxie** [comment]
Thanks for reporting the issue:) I have fixed it.
