### ISSUE TITLE
Download failed while song name containes special character.

### ISSUE THREAD

**Issue by leopku** [ziwenxie/netease-dl#2]
```
Downlaoding harmonie (Anime Ver.) 3795kb  [####################################]  100%
Downlaoding EXEC_COSMOFLIPS/. 8465kb  [------------------------------------]    0%
Traceback (most recent call last):
  File "/Users/leo/.pyenv/versions/3.5.1/bin/netease-dl", line 9, in <module>
    load_entry_point('netease-dl==1.0.1', 'console_scripts', 'netease-dl')()
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/netease/start.py", line 115, in me
    netease.download_person_playlists()
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/netease/download.py", line 60, in wrapper
    result = method(*args, **kwargs)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/netease/download.py", line 243, in download_person_playlists
    self.download_user_playlists_by_id(user_id)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/netease/download.py", line 232, in download_user_playlists_by_id
    playlist.playlist_id, playlist.playlist_name)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/netease/download.py", line 30, in wrapper
    result = method(*args, **kwargs)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/netease/download.py", line 205, in download_playlist_by_id
    self.download_song_by_id(song.song_id, song.song_name, folder)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/netease/download.py", line 108, in download_song_by_id
    self.crawler.get_song_by_url(url, song_name, folder, lyric_info)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/netease/weapi.py", line 37, in wrapper
    result = method(*args, **kwargs)
  File "/Users/leo/.pyenv/versions/3.5.1/lib/python3.5/site-packages/netease/weapi.py", line 352, in get_song_by_url
    with open(fpath, 'wb') as song_file:
FileNotFoundError: [Errno 2] No such file or directory: './asdf喜欢的音乐/EXEC_COSMOFLIPS/..mp3'
```

Proposal:
replacing special characters can not to be used as filename like '/' before writing files.

**Comment by ziwenxie** [comment]
已经修复：
```bash
> netease-dl -q song -n EXEC_COSMOFLIPS
Downlaoding EXEC_COSMOFLIPS 8465kb  [####################################]  100% 
```

**Comment by leopku** [comment]
It seems downloading still broken.

This is a playlist for testing:
http://music.163.com/#/m/playlist?id=632193588

**Comment by ziwenxie** [comment]
Maybe you need to update to the latest version by `git clone`:
```
$ git clone https://github.com/ziwenxie/netease-dl
$ python3 setup.py install
```

It works well now:
```
> netease-dl playlist -i 632193588
Downlaoding EXEC_COSMOFLIPS 8465kb  [####################################]  100%
Cost 3s
```

**Comment by leopku** [comment]
I updated by `pip install -U netease-dl`.

emmm, I will try it later again.
