### ISSUE TITLE
某些歌曲文件名特殊导致报错

### ISSUE THREAD

**Issue by demostars** [ziwenxie/netease-dl#7]
您好~

首先感谢您开源的这个项目，非常棒。

在使用过程中，发现一个问题，与歌曲文件名相关的报错。

报错信息如下

```
Downlaoding ほえ? 3570kb  [------------------------------------]    0%
Traceback (most recent call last):
  File "c:\users\administrator\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Miniconda3\Scripts\netease-dl.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\miniconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\miniconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\miniconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\administrator\miniconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\miniconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\miniconda3\lib\site-packages\click\decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\users\administrator\miniconda3\lib\site-packages\netease\start.py", line 95, in playlist
    netease.download_playlist_by_id(id, 'playlist'+str(id))
  File "c:\users\administrator\miniconda3\lib\site-packages\netease\download.py", line 30, in wrapper
    result = method(*args, **kwargs)
  File "c:\users\administrator\miniconda3\lib\site-packages\netease\download.py", line 207, in download_playlist_by_id
    self.download_song_by_id(song.song_id, song.song_name, folder)
  File "c:\users\administrator\miniconda3\lib\site-packages\netease\download.py", line 110, in download_song_by_id
    self.crawler.get_song_by_url(url, song_name, folder, lyric_info)
  File "c:\users\administrator\miniconda3\lib\site-packages\netease\weapi.py", line 37, in wrapper
    result = method(*args, **kwargs)
  File "c:\users\administrator\miniconda3\lib\site-packages\netease\weapi.py", line 353, in get_song_by_url
    with open(fpath, 'wb') as song_file:
OSError: [Errno 22] Invalid argument: '.\\playlist2116053\\ほえ?.mp3'
```

类似的还有

```
Downlaoding I Know You (From The "Fifty Shades of Grey" Soundtrack) 4671kb  [------------------------------------]    0%
OSError: [Errno 22] Invalid argument: '.\\playlist2116053\\I Know You (From The "Fifty Shades of Grey" Soundtrack).mp3'
```

同样的错误，一旦出现错误就退出，可否先跳过或者采用备用命名方法，去掉某些不宜出现的字符？

感谢您的付出~打扰了~

**Comment by markx** [comment]
能不能给一个出错的歌的id，方便debug？

**Comment by demostars** [comment]
非常抱歉现在才回复

歌曲ID http://music.163.com/#/m/song?id=29583256

猜测原因是文件名（歌曲名中含有问号等Windows不支持的符号）

**Comment by markx** [comment]
@demostars 我想你是对的。 对于你给的例子，Windows文件名不支持`?`和`"`。
